export default {
  _RADIUS: 4,
  _SANGLE: 0,
  _EANGLE: 2 * Math.PI,

  LEFT_UP: 'LEFT UP',
  RIGHT_UP: 'RIGHT UP',
  LEFT_DOWN: 'LEFT DOWN',
  RIGHT_DOWN: 'RIGHT DOWN',
  CENTER: 'CENTER',

  UP: 'UP',
  BOTTOM: 'BOTTOM',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',

  TEXTBASELINE: 'middle',
  TEXTFAMILY: 'Lato',

  TOLLTIP_TANGLE_SIZE: 5,
  TOLLTIP_BETWEEN: 5,
  TOLLTIP_PADDING: 12
}
