component:
  name: homo_lr
  description: ''
  provider: fate
  version: 2.0.0-beta
  labels: []
  roles:
    - guest
    - host
    - arbiter
  parameters:
    learning_rate_scheduler:
      type: LRSchedulerParam
      default:
        method: linear
        scheduler_params:
          start_factor: 1.0
      optional: true
      description: learning rate scheduler, select method from {'step', 'linear',
        'constant'}for list of configurable arguments, refer to torch.optim.lr_scheduler
      type_meta:
        title: LRSchedulerParam
        $ref: '#/definitions/abc__LRSchedulerParam'
        definitions:
          abc__LRSchedulerParam:
            title: LRSchedulerParam
            type: object
            properties:
              method:
                title: Method
                default: constant
                type: string
              scheduler_params:
                title: Scheduler Params
                type: object
        default:
          method: linear
          scheduler_params:
            start_factor: 1.0
        description: learning rate scheduler, select method from {'step', 'linear',
          'constant'}for list of configurable arguments, refer to torch.optim.lr_scheduler
    epochs:
      type: ConstrainedNumberMeta
      default: 20
      optional: true
      description: max iteration num
      type_meta:
        title: ConstrainedNumberMeta
        exclusiveMinimum: 0
        type: integer
    batch_size:
      type: ConstrainedNumberMeta
      default: 100
      optional: true
      description: batch size, value less or equals to 0 means full batch
      type_meta:
        title: ConstrainedNumberMeta
        minimum: -1
        type: integer
    optimizer:
      type: OptimizerParam
      default:
        method: sgd
        penalty: l2
        alpha: 1.0
        optimizer_params:
          lr: 0.01
          weight_decay: 0
      optional: true
      description: ''
      type_meta:
        title: OptimizerParam
        $ref: '#/definitions/abc__OptimizerParam'
        definitions:
          abc__OptimizerParam:
            title: OptimizerParam
            type: object
            properties:
              method:
                title: Method
                default: sgd
                type: string
              penalty:
                title: Penalty
                default: l2
                type: string
              alpha:
                title: Alpha
                default: 1.0
                type: number
              optimizer_params:
                title: Optimizer Params
                type: object
            required:
              - optimizer_params
        default:
          method: sgd
          penalty: l2
          alpha: 1.0
          optimizer_params:
            lr: 0.01
            weight_decay: 0
        description: ''
    init_param:
      type: InitParam
      default:
        method: zeros
        fill_val: 0.0
        fit_intercept: true
      optional: true
      description: Model param init setting.
      type_meta:
        title: InitParam
        $ref: '#/definitions/abc__InitParam'
        definitions:
          abc__InitParam:
            title: InitParam
            type: object
            properties:
              method:
                title: Method
                default: zeros
                type: string
              fill_val:
                title: Fill Val
                default: 0.0
                anyOf:
                  - type: integer
                  - type: number
              fit_intercept:
                title: Fit Intercept
                default: true
                type: boolean
        default:
          method: zeros
          fill_val: 0.0
          fit_intercept: true
        description: Model param init setting.
    threshold:
      type: ConstrainedNumberMeta
      default: 0.5
      optional: true
      description: predict threshold for binary data
      type_meta:
        title: ConstrainedNumberMeta
        minimum: 0.0
        maximum: 1.0
        type: number
    ovr:
      type: bool
      default: false
      optional: true
      description: predict threshold for binary data
      type_meta:
        title: bool
        type: boolean
        default: false
        description: predict threshold for binary data
    label_num:
      type: ConstrainedNumberMeta
      default:
      optional: true
      description: ''
      type_meta:
        title: ConstrainedNumberMeta
        minimum: 2
        type: integer
  input_artifacts:
    data:
      train_data:
        types:
          - dataframe
        optional: false
        stages:
          - train
        roles:
          - guest
          - host
        description: ''
        is_multi: false
      validate_data:
        types:
          - dataframe
        optional: true
        stages:
          - train
        roles:
          - guest
          - host
        description: ''
        is_multi: false
      test_data:
        types:
          - dataframe
        optional: false
        stages:
          - predict
        roles:
          - guest
          - host
        description: ''
        is_multi: false
    model:
      train_input_model:
        types:
          - json_model
        optional: true
        stages:
          - train
        roles:
          - guest
          - host
        description: ''
        is_multi: false
      predict_input_model:
        types:
          - json_model
        optional: false
        stages:
          - predict
        roles:
          - guest
          - host
        description: ''
        is_multi: false
  output_artifacts:
    data:
      train_output_data:
        types:
          - dataframe
        optional: false
        stages:
          - train
        roles:
          - guest
          - host
        description: ''
        is_multi: false
      test_output_data:
        types:
          - dataframe
        optional: false
        stages:
          - predict
        roles:
          - guest
          - host
        description: ''
        is_multi: false
    model:
      train_output_model:
        types:
          - json_model
        optional: false
        stages:
          - train
        roles:
          - guest
          - host
        description: ''
        is_multi: false
    metric:
      metric:
        types:
          - json_metric
        optional: false
        stages: []
        roles: []
        description: metric, invisible for user
        is_multi: false
schema_version: v1

