name: compile the source code

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

  workflow_dispatch: {}

jobs:
  build:
    name: compile the source code
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: mvn compile
        run: mvn -DskipTests clean package

      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/fateboard-[0-9].[0-9].[0-9].jar
